# Generated by Django 5.2.8 on 2025-11-21 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=100, verbose_name='Auteur')),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(choices=[('roman', 'Roman'), ('science', 'Science'), ('histoire', 'Histoire'), ('education', 'Éducation'), ('technologie', 'Technologie'), ('culture', 'Culture Africaine'), ('religion', 'Religion'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('fichier_pdf', models.FileField(upload_to='livres/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fichier PDF')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/', verbose_name='Couverture')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('nombre_telechargements', models.IntegerField(default=0, verbose_name='Téléchargements')),
                ('nombre_lectures', models.IntegerField(default=0, verbose_name='Lectures')),
                ('ajouté_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.livre', verbose_name='Livre')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'livre')},
            },
        ),
    ]
