# Generated by Django 5.2.8 on 2025-11-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='ajouté_par',
            new_name='ajoute_par',
        ),
    ]
