# Generated by Django 5.2.8 on 2026-02-15 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_rename_ajouté_par_livre_ajoute_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 étoile - Très décevant'), (2, '2 étoiles - Décevant'), (3, '3 étoiles - Correct'), (4, '4 étoiles - Très bien'), (5, '5 étoiles - Excellent')], verbose_name='Note')),
                ('commentaire', models.TextField(help_text='Partagez votre avis sur ce livre', verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('likes', models.ManyToManyField(blank=True, related_name='avis_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='bibliotheque.livre', verbose_name='Livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
                'unique_together': {('livre', 'utilisateur')},
            },
        ),
    ]
